# Generated by Django 2.2.3 on 2019-07-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190729_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pdt_category',
            new_name='pdt_cat',
        ),
    ]
