# Generated by Django 2.2.3 on 2019-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_name', models.TextField()),
                ('war_owner_name', models.TextField()),
                ('war_email', models.TextField()),
                ('war_address', models.TextField()),
                ('war_phone', models.TextField()),
            ],
        ),
    ]
