# Generated by Django 2.2.3 on 2019-08-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField()),
                ('qty', models.TextField()),
                ('unitprice', models.TextField()),
                ('cname', models.TextField()),
                ('cnumber', models.TextField()),
                ('gst', models.TextField()),
                ('dis', models.TextField()),
                ('total', models.TextField()),
            ],
        ),
    ]
