# Generated by Django 2.2.3 on 2019-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_name', models.TextField()),
                ('qty', models.TextField()),
            ],
        ),
    ]
